logging:
  config: classpath:logback.xml
data:
  path: classpath:data.json

spring:
  datasource:
    #url: jdbc:mysql://localhost/Test_DB
#Metrics related configurations
management:
  server:
    port: 8090
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true